# Generated by Django 5.0.7 on 2024-07-22 20:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rcubeApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentmethod",
            name="order",
        ),
    ]
