# Generated by Django 5.0.7 on 2024-07-21 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rcubeApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="order",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="rcubeApp.order",
            ),
            preserve_default=False,
        ),
    ]
