# Generated by Django 5.0.7 on 2024-07-22 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rcubeApp", "0002_remove_paymentmethod_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rcubeApp.order",
            ),
        ),
    ]
