# Generated by Django 5.0.7 on 2024-07-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rcubeApp", "0002_payment_paymentmethod"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentmethod",
            name="details",
        ),
        migrations.RemoveField(
            model_name="paymentmethod",
            name="method_name",
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="address",
            field=models.CharField(default="Default Address", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="card_number",
            field=models.CharField(default="1111-2222-3333-4444", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="city",
            field=models.CharField(default="Default City", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="cvv",
            field=models.CharField(default=123, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="email",
            field=models.EmailField(default="default@example.com", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="exp_month",
            field=models.CharField(default="January", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="exp_year",
            field=models.CharField(default="2025", max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="full_name",
            field=models.CharField(default="Default Full Name", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="name_on_card",
            field=models.CharField(default="John Doe", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="state",
            field=models.CharField(default="Default State", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="zip_code",
            field=models.CharField(default="12345", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(max_length=50),
        ),
    ]
