# Generated by Django 5.0.7 on 2024-07-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rcubeApp", "0004_alter_paymentmethod_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmethod",
            name="cvv",
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="zip_code",
            field=models.CharField(max_length=6),
        ),
    ]
