# Generated by Django 5.0.7 on 2024-07-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rcubeApp", "0005_alter_paymentmethod_cvv_alter_paymentmethod_zip_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmethod",
            name="card_number",
            field=models.CharField(max_length=16),
        ),
    ]
