# Generated by Django 5.0.7 on 2024-07-15 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_visitcounter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greeninnovation',
            name='author',
        ),
        migrations.RemoveField(
            model_name='sustainableliving',
            name='author',
        ),
        migrations.AlterField(
            model_name='visitcounter',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('GREEN_INNOVATION', 'Green Innovation'), ('ECO_PRODUCTS', 'Eco Products'), ('SUSTAINABLE_LIVING', 'Sustainable Living')], default='GREEN_INNOVATION', max_length=50)),
                ('content', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.DeleteModel(
            name='EcoProducts',
        ),
        migrations.DeleteModel(
            name='GreenInnovation',
        ),
        migrations.DeleteModel(
            name='SustainableLiving',
        ),
    ]
