# Generated by Django 5.0.7 on 2024-07-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_alter_visitcounter_count_ecoproducts_greeninnovation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ecoproducts",
            name="author",
            field=models.CharField(default="Unknown Author", max_length=100),
        ),
        migrations.AlterField(
            model_name="greeninnovation",
            name="author",
            field=models.CharField(default="Unknown Author", max_length=100),
        ),
        migrations.AlterField(
            model_name="sustainableliving",
            name="author",
            field=models.CharField(default="Unknown Author", max_length=100),
        ),
    ]
